Repository Zeal-L/BiliBili-Manga-Downloader, pull requests merged in 2024-03, with the labels that each got.

#122 🐛尽力修正标题的错误替换
  src/Episode.py
Labels: bug

#123 🐛修复一个运行时错误
  src/ComicInfoXML.py
Labels: bug

#126 修复BiliPlus Cookie
  src/BiliPlus.py
  src/ui/SettingUI.py
Labels: bug

#127 Develop
  .github/workflows/pylint.yml
  README.md
  app.py
  build.sh
  poetry.lock
  pyproject.toml
  setup.sh
  src/BiliPlus.py
  src/BiliQrCode.py
  src/Comic.py
  src/ComicInfoXML.py
  src/DownloadManager.py
  src/Episode.py
  src/SearchComic.py
  src/Utils.py
  src/ui/DownloadUI.py
  src/ui/MainGUI.py
  src/ui/MangaUI.py
  src/ui/PySide_src/mainWindow.ui
  src/ui/PySide_src/mainWindow_ui.py
  src/ui/PySide_src/myAbout.ui
  src/ui/PySide_src/myAbout_ui.py
  src/ui/PySide_src/qrCode_ui.py
  src/ui/PySide_src/resource_rc.py
  src/ui/SettingUI.py
Labels: bug, enhancement, dependencies

#128 🚧 更新打包配置
  build.sh
  macos.spec
  src/ui/PySide_src/myAbout.ui
  src/ui/PySide_src/myAbout_ui.py
  src/ui/PySide_src/resource_rc.py
  version.txt
  windows.spec
Labels: enhancement

#130 :ambulance: 再次紧急修复Biliplus下载，以及优化相关文本
  README.md
  src/BiliPlus.py
  src/ui/SettingUI.py
Labels: bug

#131 Develop
  poetry.lock
  src/BiliPlus.py
  src/DownloadManager.py
  src/Episode.py
  src/ui/MangaUI.py
  src/ui/PySide_src/mainWindow.ui
  src/ui/PySide_src/mainWindow_ui.py
  src/ui/PySide_src/resource_rc.py
  src/ui/SettingUI.py
Labels: bug, enhancement
